"""comment table

Revision ID: 815cc9e9364c
Revises: a12af9f3c569
Create Date: 2019-02-11 20:57:56.773898

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '815cc9e9364c'
down_revision = 'a12af9f3c569'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=140), nullable=True),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comment_timestamp'), 'comment', ['timestamp'], unique=False)
    op.create_index(op.f('ix_category_Category'), 'category', ['Category'], unique=True)
    op.drop_index('ix_category_Category', table_name='category')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_category_Category', 'category', ['Category'], unique=1)
    op.drop_index(op.f('ix_category_Category'), table_name='category')
    op.drop_index(op.f('ix_comment_timestamp'), table_name='comment')
    op.drop_table('comment')
    # ### end Alembic commands ###
